project:
  type: book
  output-dir: docs
  
# execute:
#   keep-md: true

lang: pt-BR


book:
#  title: "Fundamentos Matemáticos e Estatísticos da Análise Multivariada"
#  subtitle: "Departamento de Estatística e Matemática Aplicada"
#  description: "Laboratório de Inovação em Estatística - StatLab"
#  author: "Grupo de Pesquisa Inovação em Estatística e Ciência de Dados"
#  date: today
  chapters:
    - index.qmd
    - prefacio_multivariada.qmd
    - identifica_multivariada.qmd
    
    - part: "Módulo I — Fundamentos Matemáticos e Geométricos da Análise Multivariada"
      chapters:
#        - modulo_I.qmd
        - mod_1_vetores.qmd ## Vetores e representação dos dados multivariados
        - mod_1_matrizes.qmd ## Álgebra matricial aplicada
        - mod_1_espacos.qmd ## Espaços vetoriais, bases e projeções
        - mod_1_transformacoes.qmd ## Transformações lineares
        - mod_1_autovetores.qmd ## Autovalores, autovetores e decomposição espectral
        - mod_1_svd.qmd ## Decomposição em Valores Singulares
        - mod_1_calculo.qmd ## Cálculo Diferencial, Integral e Matricial Aplicado à Estatística Multivariada


    - part: "Módulo II — Fundamentos Probabilísticos e Inferenciais da Análise Multivariada"
      chapters:
        - modulo_II.qmd
#        - mod_2_covariancias.qmd # Matrizes de covariâncias e correlações
#        - mod_2_normal.qmd # Distribuição Normal Multivariada
#        - mod_2_amostrais.qmd # Estatísticas Amostrais e Estimação
#        - mod_2_modelo.qmd # Modelo Linear Multivariado e Hipóteses Lineares
#        - mod_2_inferencia.qmd # Inferência Multivariada

    - part: "Módulo III — Formulação Matemática e Estatística das Técnicas Multivariadas"
      chapters:
        - modulo_III.qmd


    - references.qmd  

bibliography: references_multivariada.bib
csl: associacao-brasileira-de-normas-tecnicas.csl # Opcional: para normas ABNT

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
  pdf:
    documentclass: scrreprt
    include-in-header: cover-header.tex
    include-before-body: cover.tex

editor: source


