project:
  type: book
  output-dir: docs
  
# execute:
#   keep-md: true

lang: pt-BR


book:
#  title: "Fundamentos Matemáticos e Estatísticos da Análise Multivariada"
#  subtitle: "Departamento de Estatística e Matemática Aplicada"
#  description: "Laboratório de Inovação em Estatística - StatLab"
#  author: "Grupo de Pesquisa Inovação em Estatística e Ciência de Dados"
#  date: today
  chapters:
    - index.qmd
    - prefacio_multivariada.qmd
    - identifica_multivariada.qmd
    
    - part: "Módulo I — Fundamentos Matemáticos e Geométricos da Análise Multivariada"
      chapters:
#        - modulo_I.qmd
        - mod_1_vetores.qmd           # Vetores e representação dos dados multivariados
        - mod_1_matrizes.qmd          # Álgebra matricial aplicada
        - mod_1_espacos.qmd           # Espaços vetoriais, bases e projeções
        - mod_1_transformacoes.qmd    # Transformações lineares
        - mod_1_autovetores.qmd       # Autovalores, autovetores e decomposição espectral
        - mod_1_svd.qmd               # Decomposição em Valores Singulares
        - mod_1_calculo.qmd           # Cálculo Diferencial, Integral e Matricial Aplicado à Estatística Multivariada
        - mod_1_exc.qmd               # Exercícios do Módulo I

    - part: "Módulo II — Fundamentos Probabilísticos e Inferenciais da Análise Multivariada"
      chapters:
#        - modulo_II.qmd
        - mod_2_covariancias.qmd     # Matrizes de covariâncias e correlações
        - mod_2_normal.qmd           # Distribuição Normal Multivariada
        - mod_2_amostrais.qmd        # Estatísticas Amostrais e Estimação
        - mod_2_modelo.qmd           # Modelo Linear Multivariado e Hipóteses Lineares
        - mod_2_inferencia.qmd       # Inferência Multivariada
        - mod_2_exc.qmd               # Exercícios do Módulo I

    - part: "Módulo III — Formulação Matemática e Estatística das Técnicas Multivariadas"
      chapters:
        - modulo_III.qmd
#        - mod_3_estruturas.qmd       # Problemas e estruturas das técnicas multivariadas
#        - mod_3_cp.qmd               # Formulação da Análise de Componentes Principais
#        - mod_3_fatorial.qmd         # Formulação da Análise Fatorial
#        - mod_3_agrupamento.qmd      # Formulação da Análise de Agrupamentos
#        - mod_3_escalonamento.qmd    # Formulação do Escalonamento Multidimensional
#        - mod_3_correspondencia.qmd  # Formulação da Análise de Correspondência
#        - mod_3_manova.qmd           # Formulação da MANOVA
#        - mod_3_discriminante.qmd    # Formulação da Análise Discriminante
#        - mod_3_canonica.qmd         # Formulação da Correlação Canônica
#        - mod_3_conjunta.qmd         # Formulação da Análise Conjunta


    - references.qmd  

bibliography: references_multivariada.bib
csl: associacao-brasileira-de-normas-tecnicas.csl # Opcional: para normas ABNT

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
  pdf:
    documentclass: scrreprt
    include-in-header: cover-header.tex
    include-before-body: cover.tex

editor: source


